# In class worksheet: Pandas

#### Step 1. Read ucla_basketball.csv file and save it as df

In [25]:
import numpy as np
import pandas as pd

df = pd.read_csv("ucla_basketball.csv")
df

,Name,Game Played,Minutes,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OR,DR,REB,AST,TO,STL,BLK
0,J. Jaquez Jr,37,1229,261,543,104.0,135.0,33.0,104.0,659,95.0,209,304,87.0,67.0,57.0,22.0
1,T. Campbell,37,1188,171,452,101.0,118.0,53.0,157.0,496,17.0,79,96,186.0,58.0,46.0,NaN
2,J. Clark,30,914,148,308,67.0,96.0,26.0,79.0,389,58.0,123,181,56.0,37.0,78.0,8.0
3,A. Bailey,30,807,135,273,44.0,63.0,21.0,54.0,335,25.0,89,114,65.0,73.0,34.0,9.0
4,D. Singleton,37,1043,108,253,45.0,53.0,73.0,172.0,334,20.0,84,104,40.0,17.0,41.0,7.0
5,A. Bona,33,756,104,154,47.0,82.0,NaN,NaN,255,74.0,100,174,24.0,44.0,19.0,57.0
6,D. Andrews,36,389,46,107,14.0,21.0,13.0,41.0,119,8.0,31,39,33.0,17.0,11.0,2.0
7,A. Canka,22,120,12,27,4.0,4.0,5.0,10.0,33,9.0,7,16,4.0,6.0,4.0,1.0
8,E. Manjikian,2,3,1,2,NaN,NaN,1.0,2.0,3,NaN,1,1,NaN,NaN,NaN,NaN
9,K. Nwuba,35,439,20,32,7.0,11.0,NaN,NaN,47,28.0,30,58,12.0,14.0,5.0,21.0
10,M. Etienne,32,218,17,38,6.0,16.0,NaN,NaN,40,26.0,36,62,7.0,4.0,6.0,15.0
11,W. McClendon,27,252,10,49,6.0,10.0,2.0,28.0,28,5.0,26,31,22.0,5.0,9.0,NaN
12,R. Stong,11,22,0,6,4.0,5.0,NaN,4.0,4,1.0,7,8,NaN,NaN,NaN,NaN
13,L. Cremonesi,9,20,0,1,1.0,2.0,NaN,NaN,1,1.0,1,2,2.0,2.0,NaN,NaN

#### Step 2. Show the first 4 rows and last 2 rows

In [26]:
df.head(4)
df.tail(2)

,Name,Game Played,Minutes,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OR,DR,REB,AST,TO,STL,BLK
12,R. Stong,11,22,0,6,4.0,5.0,NaN,4.0,4,1.0,7,8,NaN,NaN,NaN,NaN
13,L. Cremonesi,9,20,0,1,1.0,2.0,NaN,NaN,1,1.0,1,2,2.0,2.0,NaN,NaN

#### Step 3. Fill NaN with 0

In [29]:
df = df.fillna(0)
df

,Name,Game Played,Minutes,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OR,DR,REB,AST,TO,STL,BLK
0,J. Jaquez Jr,37,1229,261,543,104.0,135.0,33.0,104.0,659,95.0,209,304,87.0,67.0,57.0,22.0
1,T. Campbell,37,1188,171,452,101.0,118.0,53.0,157.0,496,17.0,79,96,186.0,58.0,46.0,0.0
2,J. Clark,30,914,148,308,67.0,96.0,26.0,79.0,389,58.0,123,181,56.0,37.0,78.0,8.0
3,A. Bailey,30,807,135,273,44.0,63.0,21.0,54.0,335,25.0,89,114,65.0,73.0,34.0,9.0
4,D. Singleton,37,1043,108,253,45.0,53.0,73.0,172.0,334,20.0,84,104,40.0,17.0,41.0,7.0
5,A. Bona,33,756,104,154,47.0,82.0,0.0,0.0,255,74.0,100,174,24.0,44.0,19.0,57.0
6,D. Andrews,36,389,46,107,14.0,21.0,13.0,41.0,119,8.0,31,39,33.0,17.0,11.0,2.0
7,A. Canka,22,120,12,27,4.0,4.0,5.0,10.0,33,9.0,7,16,4.0,6.0,4.0,1.0
8,E. Manjikian,2,3,1,2,0.0,0.0,1.0,2.0,3,0.0,1,1,0.0,0.0,0.0,0.0
9,K. Nwuba,35,439,20,32,7.0,11.0,0.0,0.0,47,28.0,30,58,12.0,14.0,5.0,21.0
10,M. Etienne,32,218,17,38,6.0,16.0,0.0,0.0,40,26.0,36,62,7.0,4.0,6.0,15.0
11,W. McClendon,27,252,10,49,6.0,10.0,2.0,28.0,28,5.0,26,31,22.0,5.0,9.0,0.0
12,R. Stong,11,22,0,6,4.0,5.0,0.0,4.0,4,1.0,7,8,0.0,0.0,0.0,0.0
13,L. Cremonesi,9,20,0,1,1.0,2.0,0.0,0.0,1,1.0,1,2,2.0,2.0,0.0,0.0

#### Step 4. Compute mean for each column

In [30]:
df.mean()

Game Played     27.000000
Minutes        528.571429
FGM             73.785714
FGA            160.357143
FTM             32.142857
FTA             44.000000
3PM             16.214286
3PA             46.500000
PTS            195.928571
OR              26.214286
DR              58.785714
REB             85.000000
AST             38.428571
TO              24.571429
STL             22.142857
BLK             10.142857
dtype: float64

#### Step 5. Compute Field Goal percentage for each player

Add a new column to your pandas DataFrame with column name FGP

Field Goal Percentage (FGP) = FGM / FGA

In [32]:
df['FGP'] = df['FGM']/df['FGA']
df

,Name,Game Played,Minutes,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OR,DR,REB,AST,TO,STL,BLK,FGP
0,J. Jaquez Jr,37,1229,261,543,104.0,135.0,33.0,104.0,659,95.0,209,304,87.0,67.0,57.0,22.0,0.48
1,T. Campbell,37,1188,171,452,101.0,118.0,53.0,157.0,496,17.0,79,96,186.0,58.0,46.0,0.0,0.38
2,J. Clark,30,914,148,308,67.0,96.0,26.0,79.0,389,58.0,123,181,56.0,37.0,78.0,8.0,0.48
3,A. Bailey,30,807,135,273,44.0,63.0,21.0,54.0,335,25.0,89,114,65.0,73.0,34.0,9.0,0.49
4,D. Singleton,37,1043,108,253,45.0,53.0,73.0,172.0,334,20.0,84,104,40.0,17.0,41.0,7.0,0.43
5,A. Bona,33,756,104,154,47.0,82.0,0.0,0.0,255,74.0,100,174,24.0,44.0,19.0,57.0,0.68
6,D. Andrews,36,389,46,107,14.0,21.0,13.0,41.0,119,8.0,31,39,33.0,17.0,11.0,2.0,0.43
7,A. Canka,22,120,12,27,4.0,4.0,5.0,10.0,33,9.0,7,16,4.0,6.0,4.0,1.0,0.44
8,E. Manjikian,2,3,1,2,0.0,0.0,1.0,2.0,3,0.0,1,1,0.0,0.0,0.0,0.0,0.50
9,K. Nwuba,35,439,20,32,7.0,11.0,0.0,0.0,47,28.0,30,58,12.0,14.0,5.0,21.0,0.62
10,M. Etienne,32,218,17,38,6.0,16.0,0.0,0.0,40,26.0,36,62,7.0,4.0,6.0,15.0,0.45
11,W. McClendon,27,252,10,49,6.0,10.0,2.0,28.0,28,5.0,26,31,22.0,5.0,9.0,0.0,0.20
12,R. Stong,11,22,0,6,4.0,5.0,0.0,4.0,4,1.0,7,8,0.0,0.0,0.0,0.0,0.00
13,L. Cremonesi,9,20,0,1,1.0,2.0,0.0,0.0,1,1.0,1,2,2.0,2.0,0.0,0.0,0.00

#### Step 6. Return players who played more than 1000 minutes

In [33]:
df[df['Minutes']>1000]['Name']

0    J. Jaquez Jr
1     T. Campbell
4    D. Singleton
Name: Name, dtype: object

#### Step 7. Sort your DataFrame in a decreasing order by AST (most AST to fewest AST)

In [35]:
df.sort_values('AST',ascending=False)

,Name,Game Played,Minutes,FGM,FGA,FTM,FTA,3PM,3PA,PTS,OR,DR,REB,AST,TO,STL,BLK,FGP
1,T. Campbell,37,1188,171,452,101.0,118.0,53.0,157.0,496,17.0,79,96,186.0,58.0,46.0,0.0,0.38
0,J. Jaquez Jr,37,1229,261,543,104.0,135.0,33.0,104.0,659,95.0,209,304,87.0,67.0,57.0,22.0,0.48
3,A. Bailey,30,807,135,273,44.0,63.0,21.0,54.0,335,25.0,89,114,65.0,73.0,34.0,9.0,0.49
2,J. Clark,30,914,148,308,67.0,96.0,26.0,79.0,389,58.0,123,181,56.0,37.0,78.0,8.0,0.48
4,D. Singleton,37,1043,108,253,45.0,53.0,73.0,172.0,334,20.0,84,104,40.0,17.0,41.0,7.0,0.43
6,D. Andrews,36,389,46,107,14.0,21.0,13.0,41.0,119,8.0,31,39,33.0,17.0,11.0,2.0,0.43
5,A. Bona,33,756,104,154,47.0,82.0,0.0,0.0,255,74.0,100,174,24.0,44.0,19.0,57.0,0.68
11,W. McClendon,27,252,10,49,6.0,10.0,2.0,28.0,28,5.0,26,31,22.0,5.0,9.0,0.0,0.20
9,K. Nwuba,35,439,20,32,7.0,11.0,0.0,0.0,47,28.0,30,58,12.0,14.0,5.0,21.0,0.62
10,M. Etienne,32,218,17,38,6.0,16.0,0.0,0.0,40,26.0,36,62,7.0,4.0,6.0,15.0,0.45
7,A. Canka,22,120,12,27,4.0,4.0,5.0,10.0,33,9.0,7,16,4.0,6.0,4.0,1.0,0.44
13,L. Cremonesi,9,20,0,1,1.0,2.0,0.0,0.0,1,1.0,1,2,2.0,2.0,0.0,0.0,0.00
8,E. Manjikian,2,3,1,2,0.0,0.0,1.0,2.0,3,0.0,1,1,0.0,0.0,0.0,0.0,0.50
12,R. Stong,11,22,0,6,4.0,5.0,0.0,4.0,4,1.0,7,8,0.0,0.0,0.0,0.0,0.00

#### Step 8. Select players who shoot more than 50 three pointers (3PA>50) and compute average 3PM for those players

In [37]:
df.loc[df['3PA']>50,'3PM'].mean()

41.2

#### Step 9. Select players who play more than 800 minutes and compute the sum of their PTS.

In [38]:
df.loc[df['3PA']>50,'PTS'].sum()

2213

#### Step 10. Return FTM, FTA and DR for players in the index range 3-8 (included)

Try to use both `loc` and `iloc`

In [39]:
df.loc[3:8,['FTM','FTA','DR']]

    FTM   FTA   DR
3  44.0  63.0   89
4  45.0  53.0   84
5  47.0  82.0  100
6  14.0  21.0   31
7   4.0   4.0    7
8   0.0   0.0    1

In [40]:
df.iloc[3:8,[5,6,11]]

    FTM   FTA   DR
3  44.0  63.0   89
4  45.0  53.0   84
5  47.0  82.0  100
6  14.0  21.0   31
7   4.0   4.0    7

#### Step 11. Compute average PTS, average REB, average AST, average STL, and average BLK for each player and create a new dataFrame contains player name and computed statistics

average points = PTS/Game Played

Column names: ['name','PTS','REB','AST','STL','BLK']

In [43]:
new_df = pd.DataFrame(df['Name'])
new_df['PTS'] = df['PTS']/df['Game Played']
new_df['REB'] = df['REB']/df['Game Played']
new_df['AST'] = df['AST']/df['Game Played']
new_df['STL'] = df['STL']/df['Game Played']
new_df['BLK'] = df['BLK']/df['Game Played']
new_df

            Name        PTS       REB       AST       STL       BLK
0   J. Jaquez Jr  17.810811  8.216216  2.351351  1.540541  0.594595
1    T. Campbell  13.405405  2.594595  5.027027  1.243243  0.000000
2       J. Clark  12.966667  6.033333  1.866667  2.600000  0.266667
3      A. Bailey  11.166667  3.800000  2.166667  1.133333  0.300000
4   D. Singleton   9.027027  2.810811  1.081081  1.108108  0.189189
5        A. Bona   7.727273  5.272727  0.727273  0.575758  1.727273
6     D. Andrews   3.305556  1.083333  0.916667  0.305556  0.055556
7       A. Canka   1.500000  0.727273  0.181818  0.181818  0.045455
8   E. Manjikian   1.500000  0.500000  0.000000  0.000000  0.000000
9       K. Nwuba   1.342857  1.657143  0.342857  0.142857  0.600000
10    M. Etienne   1.250000  1.937500  0.218750  0.187500  0.468750
11  W. McClendon   1.037037  1.148148  0.814815  0.333333  0.000000
12      R. Stong   0.363636  0.727273  0.000000  0.000000  0.000000
13  L. Cremonesi   0.111111  0.222222  0.222222  0.000000  0.000000

#### Step 12. Select players who play either less than 300 minutes or less than 20 games, and then return their name, average PTS and average REB

In [48]:
condition = (df['Minutes']<300) | (df['Game Played']<20)
new_df[condition].loc[:,['Name','PTS','REB']]

            Name       PTS       REB
7       A. Canka  1.500000  0.727273
8   E. Manjikian  1.500000  0.500000
10    M. Etienne  1.250000  1.937500
11  W. McClendon  1.037037  1.148148
12      R. Stong  0.363636  0.727273
13  L. Cremonesi  0.111111  0.222222